import estrellita from "./assets/logoImperio.png";
import logoImperio from "./assets/logoImperio.png";
import HighRepublic from "./assets/HighRepublic.webp";
import JediOrder from "./assets/Jedi_Order_Symbol.webp";
import NuevaRepublica from "./assets/NuevaRepublica.svg";
import FirstOrder from "./assets/first-order.svg";
const eventos = [
    {
        titulo: "The High Republic",
        icono: HighRepublic,
        id: 1000,
        descripcion:"200 años antes del Episodio I",
        yearInicio: 382,
        tipoYearInicio: "ABY",
        yearFin: 232,
        tipoYearFin: "ABY",
        epoca: "Alta República",
        tipoEvento: "Novelas y comics",
    },
    {
        titulo: "Tales of the Jedi",
        icono: JediOrder,
        id: 1,
        descripcion:"",
        yearInicio: 36,
        tipoYearInicio: "ABY",
        yearFin: 5,
        tipoYearFin: "ABY",
        epoca: "República",
        tipoEvento: "Serie",
    },
    {
        titulo: "Episodio I La Amenaza Fantasma",
        icono: JediOrder,
        id: 2,
        descripcion:"",
        yearInicio: 32,
        tipoYearInicio: "ABY",
        yearFin: 32,
        tipoYearFin: "ABY",
        epoca: "República",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Episodio II El Ataque de los Clones",
        icono: JediOrder,
        id: 3,
        descripcion:"",
        yearInicio: 22,
        tipoYearInicio: "ABY",
        yearFin: "22",
        tipoYearFin: "ABY",
        epoca: "República",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "The Clone Wars",
        icono: JediOrder,
        id: 4,
        descripcion:"",
        yearInicio: 22,
        tipoYearInicio: "ABY",
        yearFin: 19,
        tipoYearFin: "ABY",
        epoca: "República",
        tipoEvento: "Serie",
    },
    {
        titulo: "Episodio III La venganza de los Sith",
        icono: JediOrder,
        id: 5,
        descripcion:"",
        yearInicio: 19,
        tipoYearInicio: "ABY",
        yearFin: 19,
        tipoYearFin: "ABY",
        epoca: "República",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "The Bad Batch",
        icono: logoImperio,
        id: 6,
        descripcion:"",
        yearInicio: 19,
        tipoYearInicio: "ABY",
        yearFin: 19,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Serie",
    },
    {
        titulo: "Jedi: Fallen Order",
        icono: logoImperio,
        id: 7,
        descripcion:"",
        yearInicio: 14,
        tipoYearInicio: "ABY",
        yearFin: 14,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Videojuego",
    },
    {
        titulo: "Solo: A Star Wars Story",
        icono: logoImperio,
        id: 8,
        descripcion:"",
        yearInicio: 10,
        tipoYearInicio: "ABY",
        yearFin: 10,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Obi-Wan Kenobi",
        icono: logoImperio,
        id: 9,
        descripcion:"",
        yearInicio: 9,
        tipoYearInicio: "ABY",
        yearFin: 9,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Serie",
    },
    {
        titulo: "Jedi: Survivor",
        icono: logoImperio,
        id: 10,
        descripcion:"",
        yearInicio: 9,
        tipoYearInicio: "ABY",
        yearFin: 9,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Videojuego",
    },
    {
        titulo: "Andor",
        icono: logoImperio,
        id: 11,
        descripcion:"",
        yearInicio: 5,
        tipoYearInicio: "ABY",
        yearFin: 0,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Serie",
    },
    {
        titulo: "Rebels",
        icono: logoImperio,
        id: 12,
        descripcion:"",
        yearInicio: 5,
        tipoYearInicio: "ABY",
        yearFin: 0,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Serie",
    },
    {
        titulo: "Rogue One",
        icono: logoImperio,
        id: 13,
        descripcion:"",
        yearInicio: 0,
        tipoYearInicio: "ABY",
        yearFin: 0,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Episodio IV: Una nueva esperanza",
        icono: logoImperio,
        id: 14,
        descripcion:"",
        yearInicio: 0,
        tipoYearInicio: "ABY",
        yearFin: 0,
        tipoYearFin: "ABY",
        epoca: "Imperio",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Episodio V: El imperio contraataca",
        icono: logoImperio,
        id: 15,
        descripcion:"",
        yearInicio: 3,
        tipoYearInicio: "DBY",
        yearFin: 3,
        tipoYearFin: "DBY",
        epoca: "Imperio",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Episodio VI: El retorno del jedi",
        icono: logoImperio,
        id: 16,
        descripcion:"",
        yearInicio: 4,
        tipoYearInicio: "DBY",
        yearFin: 4,
        tipoYearFin: "DBY",
        epoca: "Imperio",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Squadrons",
        icono: NuevaRepublica,
        id: 17,
        descripcion:"",
        yearInicio: 4,
        tipoYearInicio: "DBY",
        yearFin: 4,
        tipoYearFin: "DBY",
        epoca: "Nueva República",
        tipoEvento: "Videojuego",
    },
    {
        titulo: "The Mandalorian",
        icono: NuevaRepublica,
        id: 18,
        descripcion:"",
        yearInicio: 9,
        tipoYearInicio: "DBY",
        yearFin: 7,
        tipoYearFin: "DBY",
        epoca: "Nueva República",
        tipoEvento: "Serie",
    },
    {
        titulo: "The Book of Boba Fett",
        icono: NuevaRepublica,
        id: 19,
        descripcion:"",
        yearInicio: 9,
        tipoYearInicio: "DBY",
        yearFin: 9,
        tipoYearFin: "DBY",
        epoca: "Nueva República",
        tipoEvento: "Serie",
    },
    {
        titulo: "Ahsoka",
        icono: NuevaRepublica,
        id: 20,
        descripcion:"",
        yearInicio: 9,
        tipoYearInicio: "DBY",
        yearFin: 9,
        tipoYearFin: "DBY",
        epoca: "Nueva República",
        tipoEvento: "Serie",
    },
    {
        titulo: "Skeleton Crew",
        icono: NuevaRepublica,
        id: 21,
        descripcion:"",
        yearInicio: 9,
        tipoYearInicio: "DBY",
        yearFin: 9,
        tipoYearFin: "DBY",
        epoca: "Nueva República",
        tipoEvento: "Serie",
    },
    {
        titulo: "Battlefront II",
        icono: NuevaRepublica,
        id: 22,
        descripcion:"",
        yearInicio: 32,
        tipoYearInicio: "DBY",
        yearFin: 35,
        tipoYearFin: "DBY",
        epoca: "Nueva República",
        tipoEvento: "Videojuego",
    },
    {
        titulo: "Resistance",
        icono: FirstOrder,
        id: 23,
        descripcion:"",
        yearInicio: 34,
        tipoYearInicio: "DBY",
        yearFin: 35,
        tipoYearFin: "DBY",
        epoca: "Primera Orden",
        tipoEvento: "Serie",
    },
    {
        titulo: "Episodio VII: El Despertar de la Fuerza",
        icono: FirstOrder,
        id: 24,
        descripcion:"",
        yearInicio: 34,
        tipoYearInicio: "DBY",
        yearFin: 34,
        tipoYearFin: "DBY",
        epoca: "Primera Orden",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Episodio VIII: El Último Jedi",
        icono: FirstOrder,
        id: 25,
        descripcion:"",
        yearInicio: 34,
        tipoYearInicio: "DBY",
        yearFin: 34,
        tipoYearFin: "DBY",
        epoca: "Primera Orden",
        tipoEvento: "Pelicula",
    },
    {
        titulo: "Episodio IX: El Ascenso de Skywalker",
        icono: FirstOrder,
        id: 26,
        descripcion:"",
        yearInicio: 35,
        tipoYearInicio: "DBY",
        yearFin: 35,
        tipoYearFin: "DBY",
        epoca: "Primera Orden",
        tipoEvento: "Pelicula",
    },
];

export default eventos;
